### PR TITLE
chore(bot-and-integration):Modify .hound.yml

### PR DESCRIPTION
**Pull request by KaiserPhemi**
.hound.yml file was modified to resolve error
[Fixes #141409241]

### CODE REVIEW

**Comment by uopaluwa** [comment]
Fix issue with hound.

**Comment by uopaluwa** [comment]
You should resolve this issue on the branch for this chore and then make a PR, this branch doesn't follow clearly laid out naming conventions also your PR should always follow the laid convention.

**Comment by KaiserPhemi** [comment]
Ok. I tried that but got a message like `no branch to compare`. I believe it was deleted by bayo. That's why the patch branch was created

**Comment by q-ode** [comment]
@andela-oakinwa you can either create the branch again, or create a bug in PT and use that in a new branch to fix the issue as suggested by @andela-uopaluwa.

**Pull request closed without merging**
